### ISSUE TITLE
Mod Title

### ISSUE THREAD

**Issue by Buruko** [orendain/DemeoMods#123]
Seeing the game is a focus on pen & paper play the term 'House Rules' seems to jump to mind as a neat way to harken back to that style of play in this virtual environment. Purpose changing mod title to 'House Rules' to suit.

**Comment by orendain** [comment]
+1

Better than "RulesAPI", IMHO.  And better than "RuleSets/Rulesets" as it doesn't conflct w/ the actual domain specific language we use internally (e.g., `Ruleset`).

**Comment by jimconner** [comment]
I agree. 'House Rules' is better than RulesAPI. Let's change it.

**Comment by orendain** [comment]
Haven't updated any docs as part of https://github.com/orendain/DemeoMods/pull/126.  Still an outstanding task.

**Comment by orendain** [comment]
Documentation fixed by @jimconner as part of https://github.com/orendain/DemeoMods/pull/131.  Closing this issue.
