### ISSUE TITLE
Introduce a QoL ruleset based on vanilla Demeo.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#174]
Either QoL changes, or perceived "fixes".

- +1 starting strength for Sorc
- 0AP Zap
  - Or double zap cards and +1 dmg
- 0AP Bard song
- Increased bard song duration
- Or 3x3 bard song aoe

**Comment by jimconner** [comment]
We now have two QoL rulesets as JSON examples. [Better Sorcerer.json](https://github.com/orendain/DemeoMods/blob/main/docs/rulesets/Better%20Sorcerer.json) and [3x3 Potions and Buffs.json](https://github.com/orendain/DemeoMods/blob/main/docs/rulesets/3x3%20Potions%20and%20Buffs.json)

Do either of these help to close this issue, or are we wanting a built-in one?

**Comment by orendain** [comment]
Those are great rulesets.  I was thinking something along the lines of an aggregate of those types of changes.  Something that could evolve as a type of `Demeo Plus` ruleset, true to the spirit of vanilla Demeo but still significant.

Perhaps a good start for the purposes of closing the ruleset could be a JSON ruleset with the mentioned rulesets combined within in.

**Comment by Buruko** [comment]
I dunno if I would call these QoL improvements rather enhancements or balancing proposals.
