### ISSUE TITLE
List all built-in rulesets so users can link to them.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#177]
So hosts can send link to players, and players can read what the ruleset they're playing currently does.

Unfortunately, there's no way (that I've found) for the host to send this kind of arbitrary information across to other clients.  No implemented chat feature, for example.

**Comment by Buruko** [comment]
Created Ruleset header on wiki for linking, hopefully this works for your thought process.

All rulesets:
https://github.com/orendain/DemeoMods/wiki/House-Rules#rulesets

Individual ruleset:
https://github.com/orendain/DemeoMods/wiki/House-Rules#the-swirl
https://github.com/orendain/DemeoMods/wiki/House-Rules#beat-the-clock
https://github.com/orendain/DemeoMods/wiki/House-Rules#difficulty-easy
..etc..

Each ruleset has description and details, links abilities/cards to wiki for sourcing.

**Comment by orendain** [comment]
That's amazing @Buruko !  Considering this issue completed.
