### ISSUE TITLE
Display in-game error message if there was a problem loading JSON rulesets.

### ISSUE THREAD

**Issue by jimconner** [orendain/DemeoMods#192]
I make errors  in my JSON rulesets which sometimes cause them to fail to load... However, I don't realise that has happened until after I've started a game.

It would be nice to display an in-game message as early as possible to say if a ruleset has failed to load. - Having to check the melonloader logs is not good UX.

**Comment by orendain** [comment]
Great point.  A couple of clarifying questions:
1. Currently, individual rules in a ruleset are skipped if there's an error parsing that rule.  A JSON ruleset with `N` rules will load even if `N-1` rules fail - of course, it would then only have included rule.  Would you prefer that the entire ruleset be considered having failed loading unless all rules are parsed/loaded properly?
2. If the answer to the above is `Yes, fail the entire ruleset`, then is it enough for the ruleset to not appear in the in-game UI, or should there still be a notification?
3. If notification, would you prefer pop-up (like in-game welcome message, which is easy to generate but may be easily missed), or persistent message somewhere on the in-game menu (which may take some time to implement)?

**Comment by jimconner** [comment]
Currently I find it quite hard to know what ruleset is loaded until I'm actually in the game, choosing my starting character.. At that point it's nice and clear because there is a message filling my vision, listing out the rules. 
When at the home screen, clicking rulesets in the menu doesn't give any clear visual feedback that anything happened. It would be nice if the ruleset button could stay a different colour after selection, or some other indication like that - Maybe rulesets which had errors can be highlighted in some way in the menu.

Regarding the clarification points:
1.) Without an obvious error message being displayed, this behaviour is very confusing for the user. They have written their ruleset, they've played a game with it, but not all of the rules have worked. Although the errors are all present in the melonloader logs, the user has to know where to find the logs, and remember to look in there. Loading of `n-1` rules would be ideal if we can make an obvious in-game indication of the failure - if not then it would be better to fail the whole ruleset.

2.) If failing entire ruleset I think it is reasonable enough for it to just not be displayed. When the ruleset fails to appear in the game, I'd automatically start looking for log files to find out what went wrong.

3.) in-game popup is good enough for now I think. Anyone who is actually editing their own rulesets is likely to be restarting the game frequently, so even if they miss a popup one time, they'll see it sooner or later. Obviously, popup+menu-change would better, and popup+menu_change+in-game_text would be best, but it's probably not worth the effort at the moment when the number of people editing JSON rulesets can be counted on one hand.
