### ISSUE TITLE
Consider creating additional custom game rules.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#24]
- ~Player starting health adjusted~ https://github.com/orendain/DemeoMods/issues/47
- ~Pots have AoE effect~ https://github.com/orendain/DemeoMods/pull/93
- ~Sorc has 2 zaps~https://github.com/orendain/DemeoMods/issues/35
- ~non-class cards allowed when mana hits 100~  https://github.com/orendain/DemeoMods/pull/110
- ~Players start with specific cards.~ https://github.com/orendain/DemeoMods/pull/106
  - ~start w/ chest card.~
- ~assassin has reusable arrow card~  https://github.com/orendain/DemeoMods/pull/106

Universal Player game mode:
- ~Players start with all starting class cards (or random mix).~  https://github.com/orendain/DemeoMods/pull/106
- ~All players can get all class cards.~ https://github.com/orendain/DemeoMods/issues/110
- ~Increased card hand count to compensate.~ https://github.com/orendain/DemeoMods/issues/111

Hunter's paradise game mode:
- ~Only pets + turret cards + hunters mark + lures~ https://github.com/orendain/DemeoMods/issues/110
- ~Increased mana gain.~ https://github.com/orendain/DemeoMods/issues/61

Godmode but timelimit:
- ~Players have godmode and/or uber powers.~  https://github.com/orendain/DemeoMods/pull/106
- ~Game ends if players don't complete game within X rounds.~ https://github.com/orendain/DemeoMods/issues/112
- ~On each round, print number of rounds left.~ https://github.com/orendain/DemeoMods/issues/112

**Comment by orendain** [comment]
Some ideas from https://www.reddit.com/r/Demeo/comments/ou1gss/modding_demeo:

- Increase HP for Lure, Behemoths, Ballista, Verochka
- Healing ward gets 4 AP per round.
- 0AP for Wizards zap and repair armour
- Prevent enemies opening doors.
- Increase HPs replenish by potions and fountains.
- Chests give two cards
- More chest spawns

**Comment by Buruko** [comment]
Could this be leverage to perhaps Difficulty Settings? 

Like a rule set for 'Easy'
- No monster spawn
- Scaling reduced by 1 (so 4 players is like 3 and so on)

Then 'Normal' is well normal

Then 'Hard'
- Scaling increased by 1

This is also another very much requested feature

**Comment by orendain** [comment]
Hey @Buruko,

Now that a few more rules have been implemented (current list of [available rules listed here](https://github.com/orendain/DemeoMods/blob/main/Rules/README.md), which exact rules/values would you suggest exist for each ruleset?

**Comment by orendain** [comment]
Closing as rules/rulesets have been moved to their own top-level issues.
