### ISSUE TITLE
Games not correctly restored after saving.

### ISSUE THREAD

**Issue by jimconner** [orendain/DemeoMods#273]
Every time I've tried to restore a modded game from a save, the game has come back only partially modded. We've now  had a report from Solracd saying that they've experienced the same thing.

Not sure if it's an issue we can fix, but I've been forgetting to mention it for the last few weeks, so though I'd raise it as an issue here.

**Comment by orendain** [comment]
FWIW, activating HR from a save wasn't explicitly part of core.  My thinking was that (at least without some amount of work), we couldn't determine whether a save was modded in the first place.

But thinking about this for the first time in a long time, perhaps it's not our responsibility to verify/keep the integrity of a save.  If a player wants to load mods for a save, why not let them.  I'll work on this and see what we think.
