### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by TheGrayAlien** [orendain/DemeoMods#297]
Currently any of the existing mods that tries to use "Rule": "StartCardsModified" won't allow my play pieces to load after selecting them to start the game. Tested by making my own mod using the parameter and although there are no errors in the monitor it still happens. I played using steam VR version of Demeo.

Tried PC version but it says the DLL's are incompatible so it skips loading the entire House Rules mod.

**Comment by jimconner** [comment]
Hi TheGrayAlien - I think we've already fixed this issue in the code, but haven't yet made a new release set of DLLs. If you give me (Fecn) a ping on the (HouseRules Discord)[https://discord.gg/N9DZB5ebmj] channel, I'll send you over some freshly baked DLLs.

**Comment by TheGrayAlien** [comment]
Thanks, I've PM'd you on Discord about this. Appreciate the timely reply.

**Comment by jimconner** [comment]
I'm going to close this issue now as we've found the workaround. Thank you for reporting the problem @TheGrayAlien
