### ISSUE TITLE
AoE reset fails

### ISSUE THREAD

**Issue by TheGrayAlien** [orendain/DemeoMods#303]
If you play a modded game with any AoE changes and then switch to a default game it will make the previous AoE changed cards become single target. Can test by starting any AoE changed game, then quit and try to play a default game. I played a game with +1 to all AoE cards and the cards read 5x5 and spells hit 5x5 as they should. Next game I switched to default and cards read -3x-3 and all those spells would only hit a single target. Had to exit Demeo completely to reset properly.

**Comment by orendain** [comment]
Thanks for reporting this @TheGrayAlien! I'll get on this ASAP.
