### ISSUE TITLE
AbilityDamageAdjusted doesn't reset

### ISSUE THREAD

**Issue by TheGrayAlien** [orendain/DemeoMods#315]
After playtesting a few games in a row using the same mod I realized my Wizard's zap was hitting for 8 instead of 2. It seems AbilityDamageAdjusted isn't resetting after each session ends and is instead becoming additive each new successive game.

**Comment by orendain** [comment]
Great catch, @TheGrayAlien! 🙏🏾 

Looks like the issue is here: https://github.com/orendain/DemeoMods/blob/e2fabbd1f819e250884ba94b772da0ef550b6a12/HouseRules_Essentials/Rules/AbilityDamageAdjustedRule.cs#L51

Will get a fix out at some point unless someone beats me to it.

**Comment by TheGrayAlien** [comment]
Yes, that would definitely be better if it can be managed. As it is right now I can allow characters to have specified critical melee damage but can't allow it for abilities.

**Comment by orendain** [comment]
I completely agree. Definitely better to be explicit about the values to manage.

**Comment by jimconner** [comment]
Pull request for AbilityDamageOverridden rule #318 raised for review.

**Comment by orendain** [comment]
Fixed by https://github.com/orendain/DemeoMods/pull/318.
