### ISSUE TITLE
Add a rule to include allies and/or friendly monsters when using the Regroup card.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#323]
The regroup ability makes use of the `Boardgame.GameplayEffects.Teleport` sequence.  The `Teleport` sequence has a field, `teleportPieceMode`, of type `TeleportTargetPiece`, which specifies what pieces can be teleported (`Attacker`, `Defenders`, `MyTeam`).

I suspect overriding `MyTeam` to include allies and/or friendlies would result in them getting pulled in via the regroup card.

---

A related feature could also be:
Overriding `Attacker`/`Defenders` to mean not just a single target, but all nearby attackers/defenders.  This would make banish an AoE banish, and a mystic's teleport an AoE teleport.

**Comment by jimconner** [comment]
Implemented in #340 - Closing this issue.
