### ISSUE TITLE
Default Ruleset parameter inside config does not change default ruleset

### ISSUE THREAD

**Issue by Gavinboley** [orendain/DemeoMods#347]
After attempting any possible method of inputting the correct name(as filename, configured name in ruleset file, and .json added) of the ruleset which i would want to set as default, it won’t change. Even if the name contains no spaces or non characters. After briefly reviewing the code i cannot figure out where the cooresponding method to set this value is even used, it seems to be implemented but not called.

**Comment by Gavinboley** [comment]
Further, the documentation for this file is vague and weirdly formatted

**Comment by TheGrayAlien** [comment]
It's been working for me. As an example if your json starts with:
```
{
  "Name": "My Mod v2",
```
In this case you should just need to modify the MelonPreferences.cfg file in your (possibly) C:\Program Files (x86)\Steam\steamapps\common\Demeo\UserData directory to appear as below:
```
[HouseRules]
defaultRuleset = "My Mod v2"
loadRulesetsFromConfig = true
```
It is also possible that you have a different cfg filename as that was incorrect on the HR website until a couple weeks ago so make sure it is name MelonPreferences.cfg in the correct directory.

**Comment by jimconner** [comment]
Closing this issue is we've not been able to reproduce.
