### ISSUE TITLE
PC Edition bug - StartCardsModified Rule

### ISSUE THREAD

**Issue by TheGrayAlien** [orendain/DemeoMods#393]
If you place any non-standard (blue shield) card into StartCardsModified the game plays fine, but for PC Edition players when you get to the store you can't Buy/Sell, Save, or hit Ready and have to end task on the game to get out. This happens if you're in skirmish or hosting multiplayer with PC Edition. The same happens to PC Edition clients in multiplayer when the game is hosted by either PC Edition or PC VR. This isn't the case with PC VR hosts and clients.

**Comment by TheGrayAlien** [comment]
Looks like the Card Shop for PC Edition must be relying on CardConfigDTO data of what is already in the players' hands to determine what cards it places in the shop. When I added "ScabRat" card to a players' class cards it had a blue shield and since it's listed in the DTO as costing 5  gold it didn't cause the shop problem, however the shop did give me the options to buy the "DigRatsNest" and "RatWhisperer" cards for that character only. I could buy and use them in the next map. The VR version of the shop doesn't have this restriction/feature and hopefully never will.

**Comment by jimconner** [comment]
Is this still an issue since v1.19 released? KHyperia said she'd got a fix into the 'next release' about four days before this version came out. It might be fixed inside the Demeo codebase now.

**Comment by TheGrayAlien** [comment]
Nope, works great now since v1.19! =)
