### ISSUE TITLE
RoomNumber type exception on load

### ISSUE THREAD

**Issue by sirjake1990** [orendain/DemeoMods#419]
![melonloader-roomnumber-error](https://user-images.githubusercontent.com/31493067/193196893-29470aa2-6510-4663-a8c0-99b9d3200bd7.png)

**Using Melonloader 0.5.3 - That's the issue above**, although all other mods work, this one throws this exception.

Using Melonloader 0.5.4 - I don't see any UI changes, it seems to think my PC is VR...

Using Melonloader 0.5.5 - Demeo doesn't launch.

**Comment by jimconner** [comment]
Hi @sirjake1990 - I've fixed up the code  for this mod already, but @orendain has been away for a few months and he's the only one who can configure the automated builds we have on github. I posted the fixed DLL onto the demeo-modding discord on the #general challen on 12th September - Are you able to fetch it from there? If not I'll find some other way to get it over to you.

**Comment by sirjake1990** [comment]
That did it! Thank you so much!
