### ISSUE TITLE
Add rule to adjust wolf companion starting health.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#46]
Inspired by @jimconner's tweaks, as shared in the [Demeo modding wiki](https://wiki.demeomods.xyz/unityexplorer-guide/unityexplorer-tweaking/).

The following rule may be a good reference point, as it too makes adjustments to a `PieceConfig` : https://github.com/orendain/DemeoMods/blob/main/Rules/Rule/BallistaActionPointsAdjustedRule.cs

**Comment by jimconner** [comment]
Thanks Mex - Just got RulesAPI/Rules to build for the first time and am about to give it a try. I'll see if I can knock up a rule for AOE speed/strength potions.
