### ISSUE TITLE
Add rule to set start cards.

### ISSUE THREAD

**Issue by orendain** [orendain/DemeoMods#80]
Target input could be something like:

```
- HeroClass: string
- Array of cards to grant
  - cardname: string
  - isReplenishable: bool
```

The code to patch doesn't deal in strings, but rather enums (i.e., integers).

It's trivial to map hero classes to their respective enum, given there's only 4 of them.  But with so many abilities/cards, I propose to just take ints as input.

Resulting in:

```
- HeroClass: string
- Array of cards to grant
  - abilityKey: int
  - isReplenishable: bool
```

**Comment by jimconner** [comment]
Would we want this rule to also allow setting the number of cards which can be held? Given that Hunter can hold 11, there must bve a parameter somewhere that we can change.

**Comment by orendain** [comment]
So it turns out the game is configured to allow a max of 2 replenishable cards.

Replenishable cards add +1 each to the max card count (9 + that count).

I remember playing around w/ setting max hand size a long time ago, but can't recall if that was possible to control host-side (there might be some hardcoded client-side logic there).  I'll report back what I find.
